# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c0c8f32341acf2b62b8e031a9b56a40cfab0f3050d99f46dca190bf1bd9f040ecdf6b2860d4f500c840c581df2ba66367208b7ce690e33fe2ef73787987080a

test:
  secret_key_base: fbd494f94c320909c76578f78237c685b2d9912bd134536359a0cbc0425e771f66ffca4ddae2df378a6e46ce98c5296999e15ac5c12a16ae4c8a2b7c66ccf06d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
